import {text as e,icon,avatar} from './components.js';
import {interestChoices} from './onboarding.js';
const action=(label,name,attrs='',cls='')=>`<button class="btn ${cls}" data-action="${name}" ${attrs}>${label}</button>`;
const heading=(title,sub)=>`<header class="head"><h1>${title}</h1><p>${sub}</p></header>`;
const face=(name,url)=>url&&/^(https:\/\/|\/assets\/)/.test(url)?`<img class="bell-face" src="${e(url)}" alt="${e(name)}" loading="lazy" referrerpolicy="no-referrer">`:avatar(name);
export function communityView(state){
  const candidate=state.candidates.find(c=>c.address===state.echoAddress),preview=state.preview||state.previewOnly;
  const back=action(icon('back')+' 共鸣雷达','discover','','light compact');
  if(state.route==='echo-results')return resultsView(state,back,preview);
  if(state.route==='echo-detail')return detailView(state,candidate,back);
  if(state.route==='echo-chat'&&!state.echoAddress&&state.connections?.length)return back+heading('Echo Connections','每一份回应，都由你自己决定。')+state.connections.map(connection=>{const incoming=connection.recipient.toLowerCase()===state.user?.toLowerCase(),peer=incoming?connection.requester:connection.recipient;return `<article class="card"><div class="row">${avatar(peer)}<div><h3>${e(peer.slice(0,6)+'…'+peer.slice(-4))}</h3><p class="small muted">${e({pending:'等待回应',accepted:'已同意连接',declined:'已拒绝',blocked:'已屏蔽'}[connection.status]||connection.status)}</p></div></div><div class="actions">${incoming&&connection.status==='pending'?action('接受连接','connection-respond',`data-id="${e(connection.id)}" data-decision="accept"`,'rose')+action('暂不连接','connection-respond',`data-id="${e(connection.id)}" data-decision="decline"`,'light'):''}${action('查看连接空间','echo-chat',`data-address="${e(peer)}"`,'light')}</div></article>`;}).join('');
  if(state.route==='echo-chat')return chatView(state,candidate,back);
  return undefined;
}
function chatView(state,candidate,back){
  const connection=(state.connections||[]).find(c=>[c.requester,c.recipient].some(a=>a.toLowerCase()===state.echoAddress?.toLowerCase()));
  const incoming=connection?.status==='pending'&&connection.recipient.toLowerCase()===state.user?.toLowerCase();
  const status={pending:'等待回应',accepted:'已同意连接',declined:'已拒绝',blocked:'连接已屏蔽'};
  const response=incoming?`<div class="actions">${action('接受连接','connection-respond',`data-id="${e(connection.id)}" data-decision="accept"`,'rose')}${action('暂不连接','connection-respond',`data-id="${e(connection.id)}" data-decision="decline"`,'light')}</div>`:!connection&&candidate?action('发送连接请求','echo-connect',`data-address="${e(candidate.address)}"`,'rose'):'';
  const name=candidate?.name||state.echoAddress;
  const header=`<div class="bell-chat-header">${face(candidate?.name||state.echoAddress,candidate?.avatarUrl)}<div><h2>${e(name||'Echo Chat')}</h2><small>${connection?e(status[connection.status]||connection.status):'尚未建立连接'}</small></div></div>`;
  const ephemeral=Boolean(state.ephemeralRoom),messages=state.chatMessages||[];
  const time=at=>new Date(at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
  const dayLabel=ts=>{const d=new Date(ts),n=new Date();const same=(a,b)=>a.toDateString()===b.toDateString();const y=new Date(n);y.setDate(n.getDate()-1);return same(d,n)?'今天':same(d,y)?'昨天':d.toLocaleDateString('zh-CN',{month:'long',day:'numeric'});};
  const grouped=()=>{let out='',last='';for(const m of messages){const label=dayLabel(m.content?.at||m.created_at);if(label!==last){out+='<span class="bell-chat-day">'+e(label)+'</span>';last=label;}out+=bubble(m);}return out;};
  const bubble=m=>`<div class="bell-chat-bubble ${m.mine?'mine':'theirs'}${m.expires_at?' is-ephemeral':''}">${m.error?`<p class="small muted">${e(m.error)}</p>`:`<p>${e(m.content?.text||'')}</p>`}<small>${m.mine?'你':e(name||'对方')} · ${e(time(m.content?.at||m.created_at))}${m.expires_at?' · ⏱ '+e(Math.max(1,Math.ceil((m.expires_at-Date.now())/60000))+' 分钟后消散'):''}</small></div>`;
  return `<div class="stitch-chat">`+back+header+(connection?.status!=='accepted'
    ?`<div class="bell-conversation"><span class="pill">这是你们开始了解的地方</span><div class="bell-empty-art">${icon('heart')}<h3>先从一次双向的同意开始</h3><p>${connection?.status==='pending'?'连接请求已保存在服务器，等待对方独立决定。':'连接请求会发送给真实账户，对方可以接受或拒绝。'}</p>${response}</div></div><p class="small muted">双方同意后，这里才会打开端到端加密的对话空间。</p>`
    :(ephemeral?`<aside class="bell-ephemeral-note">${icon('clock')}<div><h3>阅后即焚空间 · 零链上痕迹</h3><p>Burn After Reading：消息只保留 24 小时，之后由服务器自动删除，不留任何链上记录，双方都无法找回。</p></div></aside>`:'')+`<div class="bell-conversation">${messages.length?grouped():`<div class="bell-empty-art">${icon('spark')}<h3>${ephemeral?'说一句只属于此刻的话':'第一句话，由你来写'}</h3><p>消息在本机加密后才离开你的设备；对方用自己的密钥解密，服务器只保存密文。</p></div>`}</div><form class="bell-composer" data-form="chat-compose"><label class="sr-only" for="chat-message">加密消息</label><input id="chat-message" name="message" maxlength="2000" placeholder="${ephemeral?'写一句只保留 24 小时的话…':'写一句想说的话…'}" autocomplete="off"><button class="icon" type="submit" aria-label="发送加密消息">${icon('send')}</button></form><div class="actions">${action(ephemeral?'返回常驻对话':'进入阅后即焚空间','ephemeral-toggle','','light compact')}</div><p class="small muted">${ephemeral?'这些消息将在 24 小时后被服务器删除。':'消息会保存在你们的连接空间，直到一方屏蔽连接。'}发送前请确认对方已完成加密密钥登记。</p>`)+`</div>`;
}
function connectionFor(state,address){return (state.connections||[]).find(c=>[c.requester,c.recipient].some(a=>a.toLowerCase()===address?.toLowerCase()));}
function resultsView(state,back,preview){
  return back+heading('People who might resonate','先看见一个人，再决定是否靠近。')+(state.candidates.length?`<div class="bell-result-summary"><span>${icon('spark')} ${state.candidates.length} 位公开资料</span><small>来自共同兴趣与关系意向</small></div><div class="bell-echo-grid">${state.candidates.map(c=>{
    const shared=c.interests.filter(i=>state.profile?.interests?.includes(i)),connection=connectionFor(state,c.address);
    return `<article class="bell-echo-card"><button class="bell-portrait" data-action="echo-detail" data-address="${e(c.address)}" aria-label="查看 ${e(c.name)}">${face(c.name,c.avatarUrl)}<span class="bell-portrait-caption">${icon('spark')}${shared.length?'共同喜欢 '+e(shared.slice(0,2).join(' · ')):'从一次了解开始'}</span></button><div class="row"><h2>${e(c.name)}${c.age?', '+e(c.age):''}</h2>${connection?.status==='accepted'?'<span class="pill ok">已同意连接</span>':''}</div><p class="small muted">${icon('pin')}${e(c.city||'城市未填写')}${c.occupation?' · '+e(c.occupation):''}</p><div class="chips">${c.interests.map(i=>`<span class="pill">${e(i)}</span>`).join('')}</div><p class="bell-card-introduction">${e(c.statement||'让第一次对话，成为了解的开始。')}</p><div class="row">${action(icon('heart'),'radar-save',`data-address="${e(c.address)}" aria-label="${c.saved?'取消收藏':'收藏'} ${e(c.name)}" aria-pressed="${Boolean(c.saved)}"`,'light compact')}${action('了解彼此 '+icon('next'),'echo-detail',`data-address="${e(c.address)}"`,'rose compact')}</div></article>`;
  }).join('')}</div>`:`<div class="bell-empty-art">${icon('bell')}<h2>等待一份真实的共鸣</h2><p>登录并完善资料后，开始寻找与你兴趣相近的人。</p>${action(preview?'连接钱包':'重新探测',preview?'login':'discover')}</div>`);
}
function detailView(state,candidate,back){
  if(!candidate)return back+heading('Possible Echo','先在共鸣雷达选择一位真实候选人。')+action('查看推荐结果','echo-results');
  const connection=connectionFor(state,candidate.address),accepted=connection?.status==='accepted',pending=connection?.status==='pending';
  const reasons=candidate.reasons||[],common=candidate.interests.filter(i=>state.profile?.interests?.includes(i));
  const distance=candidate.distanceKm===null||candidate.distanceKm===undefined?'':candidate.distanceKm===0?' · 同一粗略区域':' · 区域估算约 '+candidate.distanceKm+' km';
  return back+(accepted?`<aside class="bell-match-notice">${icon('heart')}<div><h3>你们都选择了连接</h3><p>双方已同意在 Echo 中继续了解彼此。</p></div><span class="pill ok">链下连接</span></aside>`:'')+`<article class="bell-profile-card"><div class="bell-profile-hero">${face(candidate.name,candidate.avatarUrl)}<span class="bell-profile-label">${icon('spark')}${common.length?'共同兴趣 · '+common.length+' 项':'公开资料'}</span><h1>${e(candidate.name)}${candidate.age?', '+e(candidate.age):''}</h1><p>${candidate.occupation?e(candidate.occupation)+' · ':''}${icon('pin')}${e(candidate.city||'城市未填写')}${e(distance)}</p></div><div class="bell-profile-body"><div class="chips">${candidate.interests.map(i=>`<span class="pill">${e(i)}</span>`).join('')}</div><blockquote class="bell-introduction">“${e(candidate.statement||'对方还没有填写自我介绍。')}”</blockquote></div></article><section class="bell-reasons"><div class="row"><h2>Why you resonated</h2><span class="small muted">资料推荐</span></div>${reasons.map((reason,index)=>`<div class="bell-reason"><span class="bell-setting-icon">${icon(['image','heart','book'][index%3])}</span><div><h3>${e(reason)}</h3><p>${['从彼此公开的兴趣里，寻找一个话题。','关系意向来自本人填写，仍需要彼此了解。','每一份回应，都由你们各自决定。'][index%3]}</p></div></div>`).join('')||'<p>还没有足够资料生成推荐理由。</p>'}<small class="muted">匹配不代表身份核验、链上证明或关系成立。</small></section><div class="bell-profile-consent">${icon('shield')}<p>Echo 可以连接多人；Romantic Ring 的建立仍需两个人独立的钱包确认。</p></div><div class="actions">${action(accepted?'进入连接空间 '+icon('next'):pending?'查看等待中的请求':"Let's Connect",accepted||pending?'echo-chat':'echo-connect',`data-address="${e(candidate.address)}"`,'rose')}${action('了解 Ring 邀请','invite',`data-address="${e(candidate.address)}"`,'light')}</div>`;
}
